# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listado.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_listado(object):
    def setupUi(self, listado):
        listado.setObjectName("listado")
        listado.setWindowModality(QtCore.Qt.ApplicationModal)
        listado.resize(850, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(listado.sizePolicy().hasHeightForWidth())
        listado.setSizePolicy(sizePolicy)
        listado.setMinimumSize(QtCore.QSize(850, 650))
        listado.setMaximumSize(QtCore.QSize(850, 650))
        self.centralwidget = QtWidgets.QWidget(listado)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 801, 61))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tb_list = QtWidgets.QTableWidget(self.centralwidget)
        self.tb_list.setEnabled(True)
        self.tb_list.setGeometry(QtCore.QRect(10, 60, 800, 550))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_list.sizePolicy().hasHeightForWidth())
        self.tb_list.setSizePolicy(sizePolicy)
        self.tb_list.setMinimumSize(QtCore.QSize(0, 0))
        self.tb_list.setMaximumSize(QtCore.QSize(800, 550))
        self.tb_list.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tb_list.setAutoFillBackground(True)
        self.tb_list.setAutoScrollMargin(16)
        self.tb_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tb_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_list.setIconSize(QtCore.QSize(0, 0))
        self.tb_list.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tb_list.setGridStyle(QtCore.Qt.SolidLine)
        self.tb_list.setColumnCount(5)
        self.tb_list.setObjectName("tb_list")
        self.tb_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tb_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tb_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tb_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tb_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tb_list.setHorizontalHeaderItem(4, item)
        self.tb_list.horizontalHeader().setCascadingSectionResizes(False)
        self.tb_list.horizontalHeader().setMinimumSectionSize(50)
        self.tb_list.horizontalHeader().setSortIndicatorShown(True)
        self.tb_list.horizontalHeader().setStretchLastSection(True)
        self.tb_list.verticalHeader().setMinimumSectionSize(50)
        self.tb_list.verticalHeader().setStretchLastSection(False)
        listado.setCentralWidget(self.centralwidget)
        self.actionActualizar = QtWidgets.QAction(listado)
        self.actionActualizar.setObjectName("actionActualizar")

        self.retranslateUi(listado)
        QtCore.QMetaObject.connectSlotsByName(listado)

    def retranslateUi(self, listado):
        _translate = QtCore.QCoreApplication.translate
        listado.setWindowTitle(_translate("listado", "Catalogo de Recetas"))
        self.label.setText(_translate("listado", "LISTADO DE RECETAS DISPONIBLE"))
        item = self.tb_list.horizontalHeaderItem(0)
        item.setText(_translate("listado", "PLATO"))
        item = self.tb_list.horizontalHeaderItem(1)
        item.setText(_translate("listado", "NOMBRE"))
        item = self.tb_list.horizontalHeaderItem(2)
        item.setText(_translate("listado", "TIEMPO"))
        item = self.tb_list.horizontalHeaderItem(3)
        item.setText(_translate("listado", "AUTOR"))
        item = self.tb_list.horizontalHeaderItem(4)
        item.setText(_translate("listado", "PUBLICACIÓN"))
        self.actionActualizar.setText(_translate("listado", "Actualizar"))

